ITEM.name = "Bandage"
ITEM.model = Model("models/illusion/eftcontainers/bandage.mdl")
ITEM.description = "An Imperial standard supply bandage"
ITEM.category = "Medical"
ITEM.noBusiness = true
ITEM.width = 1
ITEM.height = 1
ITEM.weight = .5
ITEM.maxStacks = 2