ITEM.name = "Crafting Box"
ITEM.description = "A container to hold crafting materials."
ITEM.model = Model("models/illusion/eftcontainers/magbox.mdl")
ITEM.noBusiness = true
ITEM.width = 3
ITEM.height = 2
ITEM.invWidth = 7
ITEM.invHeight = 7
ITEM.maxStacks = 1
ITEM.weight = 1.5