ITEM.name = "Docs bag"
ITEM.description = "Store important documents you find here for safe keeping"
ITEM.model = Model("models/illusion/eftcontainers/docbag.mdl")
ITEM.category = "Containers"
ITEM.width = 2
ITEM.height = 1
ITEM.invWidth = 4
ITEM.invHeight = 4
ITEM.maxStacks = 1
ITEM.weight = .5