ITEM.name = "Food Cooler"
ITEM.description = "This cooler will keep your consumable items fresh and tasty"
ITEM.model = Model("models/illusion/eftcontainers/thermobag.mdl")
ITEM.category = "Containers"
ITEM.width = 3
ITEM.height = 3
ITEM.invWidth = 7
ITEM.invHeight = 7
ITEM.maxStacks = 1
ITEM.weight = 1.5