ITEM.name = "Weapon Case"
ITEM.description = "A container used to hold weapons or weapon parts."
ITEM.model = Model("models/illusion/eftcontainers/weaponcase.mdl")
ITEM.noBusiness = true
ITEM.width = 5
ITEM.height = 2
ITEM.invWidth = 4
ITEM.invHeight = 10
ITEM.maxStacks = 1
ITEM.weight = 2